# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 511)
        MainWindow.setMinimumSize(QtCore.QSize(872, 511))
        MainWindow.setMaximumSize(QtCore.QSize(872, 511))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0.435644, y1:0.767, x2:1, y2:0, stop:0 rgba(69, 20, 68, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Header_Label = QtWidgets.QLabel(self.centralwidget)
        self.Header_Label.setGeometry(QtCore.QRect(50, 50, 811, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.Header_Label.setFont(font)
        self.Header_Label.setStyleSheet("color: rgb(255, 255, 255);")
        self.Header_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Header_Label.setObjectName("Header_Label")
        self.ID_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ID_input.setGeometry(QtCore.QRect(310, 220, 271, 51))
        self.ID_input.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.Password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_input.setGeometry(QtCore.QRect(310, 300, 271, 51))
        self.Password_input.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Password_input.setObjectName("Password_input")
        self.ID_Label = QtWidgets.QLabel(self.centralwidget)
        self.ID_Label.setGeometry(QtCore.QRect(260, 230, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.ID_Label.setFont(font)
        self.ID_Label.setStyleSheet("color: rgb(255, 255, 255);")
        self.ID_Label.setObjectName("ID_Label")
        self.Password_Label = QtWidgets.QLabel(self.centralwidget)
        self.Password_Label.setGeometry(QtCore.QRect(150, 310, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.Password_Label.setFont(font)
        self.Password_Label.setStyleSheet("color: rgb(255, 255, 255);")
        self.Password_Label.setObjectName("Password_Label")
        self.Error_Label = QtWidgets.QLabel(self.centralwidget)
        self.Error_Label.setGeometry(QtCore.QRect(240, 408, 421, 71))
        self.Error_Label.setStyleSheet("color: rgb(255, 0, 4);\n"
"font: 18pt \"Arial Rounded MT Bold\";")
        self.Error_Label.setText("")
        self.Error_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Error_Label.setObjectName("Error_Label")
        self.BelowHeader_Label = QtWidgets.QLabel(self.centralwidget)
        self.BelowHeader_Label.setGeometry(QtCore.QRect(250, 110, 391, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.BelowHeader_Label.setFont(font)
        self.BelowHeader_Label.setStyleSheet("color: rgb(255, 255, 255);")
        self.BelowHeader_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.BelowHeader_Label.setObjectName("BelowHeader_Label")
        self.Enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.Enter_button.setGeometry(QtCore.QRect(400, 370, 93, 28))
        self.Enter_button.setObjectName("Enter_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Header_Label.setText(_translate("MainWindow", "New Employee Information"))
        self.ID_Label.setText(_translate("MainWindow", "ID:"))
        self.Password_Label.setText(_translate("MainWindow", "Password:"))
        self.BelowHeader_Label.setText(_translate("MainWindow", "Please enter your manager credentials."))
        self.Enter_button.setText(_translate("MainWindow", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
